### ISSUE TITLE
Easy bug reporting

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_2#350] opened 2021-07-17 16:25 UTC
Idea:
Add a question mark icon (or smth similar) to the top-right of the popup window and once clicked, it shows some basic help information (link to torntools server homepage (coming soon™); link to discord; etc.) and a bug report form.

The form would have some general selectors like "broken feature", "layout issues", etc. and a text field for extra info. Submitting the report would send it to TT server API. All reports would be visible via browser. But the server would also send out an automatic notification to discord when a certain category has X amount of reports in Y time.

I also thought about sending the URL for extra automation. For example "There have been X reports in Y minutes about Layout issues on Home page. More details: [link]".

This would achieve multiple things:
  1) all bug reports (mostly) in one place
  2) less repeating bug reports in my mailbox & in discord

(this might bring the report numbers up actually but it's rather a good thing for the automated notifications)

**Comment by DeKleineKobini** [comment] 2021-07-18 09:37
I think the popup is already pretty crowded. Adding a icon, that wouldn't be used much anyway, as people will keep using the ways they already know.

As for the site, it's a though one for me. Having everything in one place is great, but people will keep posting duplicates (see B&I in Torn) and it introduces yet another platform.

**Comment by Sashank999** [comment] 2021-07-20 11:14
No, we better use the TT itself as a place of bug report.
Maybe a new html page like `report.html` will work.
This will prevent any spam or duplicates. We could also show a warning. But still, the site serves as a place to view the reports, closed or open.

I think of it like this:

1. User clicks on the red green `?` on the popup which redirects him to TT Bug Report Page.
2. This bug report page contains :
- A bug title field
- A text area describing the ways to reproduce the bug
- A screenshot of the bug
3. Once clicked `Submit`, the info will be sent to the API at TT Server.
4. A unique ID, maybe just consecutive number, will be assigned to the bug report, which will also be returned to the API request.
5. TT then redirects user to the bug report page.

The server has all the bug reports. Bug reports closed, either because the bug is already reported or because the bug is fixed, will be deleted within 1 month. Any duplicate bug reports will be immediately merged into the first bug report, then duplicate will be closed.

The bug reports that are successfully merged will have the Github PR or Commit's link in the closing message.

**Comment by Mephiles** [comment] 2021-07-20 11:38
Actually, that was not my point.

Currently, we track bug reports on Github only (track = close them, link them to PRs, etc.). All serious bugs should be listed in Github and closed when they're resolved.

 And then we have untracked bug reports on Discord, Torn forum, our mailboxes, etc.

The difference is that tracked bug reports don't usually have duplicates, untracked ones have duplicates and that's nothing we can resolve.

My idea of the bug report button would just make it so that majority of untracked bug reports are sent to one place. I don't want to create some extra tasks of tracking those. If we get 100 reports on visual issues on Home page then I'd rather have all these 100 in one place & then we can create 1 actual bug issue on Github.

**Comment by Mephiles** [comment] 2021-07-20 11:47
> I think the popup is already pretty crowded. Adding a icon, that wouldn't be used much anyway, as people will keep using the ways they already know.

I think this will be most used once people see it being there and understand it should be a dedicated place for bug reports.

> As for the site, it's a though one for me. Having everything in one place is great, but people will keep posting duplicates (see B&I in Torn) and it introduces yet another platform.

Like I said in my previous post, these will be untracked and most posts can be ignored. The reason why ppl post in Discord, Torn forum and our mailboxes is because we don't have a dedicated place yet for bug reports.

**Comment by DeKleineKobini** [comment] 2021-11-12 18:10
Moved to normal repo.

**Closed by DeKleineKobini** 2021-11-12 18:10 UTC
